In [1]:
from google.colab import drive
drive.mount('/content/drive')
import os
import pandas as pd

Mounted at /content/drive

In [2]:
import numpy as np


def train_test_val(df, train_percent = 0.6,val_percent = 0.2, seed = None):
  np.random.seed(seed)
  perm = np.random.permutation(df.index)

  m = len(df.index)
  train_end = int(train_percent*m)
  val_end = int(val_percent*m) + train_end

  train = df.iloc[perm[:train_end]]
  vali = df.iloc[perm[train_end:val_end]]
  test = df.iloc[perm[val_end:]]

  return train, vali, test

In [5]:
df = pd.read_csv('/content/drive/MyDrive/FullText.csv', index_col = False)

In [6]:
train, validate, test = train_test_val(df)

train

,Unnamed: 0,News,Summary,Field
3242,3242,"Howard's unfinished business\n\n""He's not fini...","Mr Howard claimed, with some justification, th...",Politics
192,192,Consumers drive French economy\n\nFrance's eco...,"""In the beginning of 2004, growth was mainly d...",Business
1097,1097,Tsunami 'won't divert Africa aid'\n\nUK aid to...,"Ahead of Sunday's meeting in London, Ms Hewitt...",Politics
597,597,Rap boss arrested over drug find\n\nRap mogul ...,He was driving Shakur's car at the time and wa...,Entertainment
710,710,Oscar host Rock to keep it clean\n\nOscar host...,The 40-year-old comedian caused a furore when ...,Entertainment
...,...,...,...,...
2352,2352,South African car demand surges\n\nCar manufac...,"New vehicle sales jumped 22% to 449,603 from a...",Business
339,339,Dollar hits new low versus euro\n\nThe US doll...,The US dollar has continued its record-breakin...,Business
2215,2215,Bank holds interest rate at 4.75%\n\nThe Bank ...,CBI chief economist Ian McCafferty said the ec...,Business
695,695,BBC 'should allow more scrutiny'\n\nMPs have u...,The report said the Freeview digital service h...,Entertainment
2382,2382,Wal-Mart fights back at accusers\n\nTwo big US...,"Meanwhile, drugs group Eli Lilly is planning a...",Business

In [7]:
train = train.drop(columns = ['Unnamed: 0'], axis = 1)
train = train.reset_index()
train = train.drop(columns = ['index'], axis = 1)

In [8]:
train

,News,Summary,Field
0,"Howard's unfinished business\n\n""He's not fini...","Mr Howard claimed, with some justification, th...",Politics
1,Consumers drive French economy\n\nFrance's eco...,"""In the beginning of 2004, growth was mainly d...",Business
2,Tsunami 'won't divert Africa aid'\n\nUK aid to...,"Ahead of Sunday's meeting in London, Ms Hewitt...",Politics
3,Rap boss arrested over drug find\n\nRap mogul ...,He was driving Shakur's car at the time and wa...,Entertainment
4,Oscar host Rock to keep it clean\n\nOscar host...,The 40-year-old comedian caused a furore when ...,Entertainment
...,...,...,...
2303,South African car demand surges\n\nCar manufac...,"New vehicle sales jumped 22% to 449,603 from a...",Business
2304,Dollar hits new low versus euro\n\nThe US doll...,The US dollar has continued its record-breakin...,Business
2305,Bank holds interest rate at 4.75%\n\nThe Bank ...,CBI chief economist Ian McCafferty said the ec...,Business
2306,BBC 'should allow more scrutiny'\n\nMPs have u...,The report said the Freeview digital service h...,Entertainment
2307,Wal-Mart fights back at accusers\n\nTwo big US...,"Meanwhile, drugs group Eli Lilly is planning a...",Business

In [9]:
test = test.drop(columns = ['Unnamed: 0'], axis = 1)
test = test.reset_index()
test = test.drop(columns = ['index'], axis = 1)

validate = validate.drop(columns = ['Unnamed: 0'], axis = 1)
validate = validate.reset_index()
validate = validate.drop(columns = ['index'], axis = 1)

In [10]:
test

,News,Summary,Field
0,Hi-tech posters guide commuters\n\nInteractive...,She said that there are no figures for how man...,Tech
1,Gadgets galore on show at fair\n\nThe 2005 Con...,One of the key issues for keen gadget users is...,Tech
2,"Lifestyle 'governs mobile choice'\n\nFaster, b...",Dr Bjorn said that people also used their came...,Tech
3,MP attacked by muggers in Kenya\n\nAn MP has h...,"He said in a statement: ""It was a frightening ...",Politics
4,Brown names 16 March for Budget\n\nChancellor ...,"The full Finance Bill, with the Budget measure...",Politics
...,...,...,...
766,British stars denied major Oscars\n\nBritish h...,"Cinematographer John Mathieson, who was nomina...",Entertainment
767,Security warning over 'FBI virus'\n\nThe US Fe...,An attachment in the e-mail contains the virus...,Tech
768,Digital guru floats sub-$100 PC\n\nNicholas Ne...,"He said one laptop per child could be "" very i...",Tech
769,UK rebate 'unjustified' - Chirac\n\nFrench pre...,The Tories said they would not cut spending bu...,Politics
770,Clyde 0-5 Celtic\n\nCeltic brushed aside Clyde...,": Varga 40, Thompson 48 pen, Petrov 60, Varga ...",Sport

## **Tokenization**

In [ ]:
!pip install transformers[sentencepiece] datasets sacrebleu rouge_score py7zr -q

In [ ]:
!pip install --upgrade accelerate
!pip uninstall -y transformers accelerate
!pip install transformers accelerate

In [13]:
from transformers import pipeline, set_seed
from datasets import load_dataset, load_from_disk
import matplotlib.pyplot as plt
from datasets import load_dataset
import pandas as pd
from datasets import load_dataset, load_metric

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
import torch

nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
model_ckpt = "google/pegasus-cnn_dailymail"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

In [15]:
train_lis = []
train_sum = []

import warnings
warnings.filterwarnings("ignore")

for i in range(len(train.index)):

  train_lis.append(tokenizer(train.News.iloc[i] , max_length = 1024, truncation = True ))
  with tokenizer.as_target_tokenizer():
    train_sum.append(tokenizer(train.Summary.iloc[i], max_length = 128, truncation = True ))

In [16]:
val_lis = []
val_sum = []

for i in range(len(validate.index)):

  val_lis.append(tokenizer(validate.News.iloc[i] , max_length = 1024, truncation = True ))
  with tokenizer.as_target_tokenizer():
    val_sum.append(tokenizer(validate.Summary.iloc[i], max_length = 128, truncation = True ))

In [17]:
test_lis = []
test_sum = []

for i in range(len(test.index)):

  test_lis.append(tokenizer(test.News.iloc[i] , max_length = 1024, truncation = True ))
  with tokenizer.as_target_tokenizer():
    test_sum.append(tokenizer(test.Summary.iloc[i], max_length = 128, truncation = True ))

In [19]:
final_train = pd.DataFrame(columns = ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'])
final_test = pd.DataFrame(columns = ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'])
final_validate = pd.DataFrame(columns = ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'])

In [20]:
for i in range(len(train.index)):

  final_train.loc[i] = [i,train.News.iloc[i],train.Summary.iloc[i], train_lis[i]['input_ids'],train_lis[i]['attention_mask'],train_sum[i]['input_ids']]

In [21]:
final_train

,id,dialogue,summary,input_ids,attention_mask,labels
0,0,"Howard's unfinished business\n\n""He's not fini...","Mr Howard claimed, with some justification, th...","[7720, 131, 116, 16634, 260, 198, 1097, 131, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1263, 7720, 4620, 108, 122, 181, 19056, 108, ..."
1,1,Consumers drive French economy\n\nFrance's eco...,"""In the beginning of 2004, growth was mainly d...","[21846, 919, 1775, 1968, 2481, 131, 116, 1500,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[198, 315, 109, 1427, 113, 11802, 874, 140, 31..."
2,2,Tsunami 'won't divert Africa aid'\n\nUK aid to...,"Ahead of Sunday's meeting in London, Ms Hewitt...","[61547, 13291, 1034, 23339, 131, 144, 23580, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[29499, 113, 1342, 131, 116, 988, 115, 1169, 1..."
3,3,Rap boss arrested over drug find\n\nRap mogul ...,He was driving Shakur's car at the time and wa...,"[21820, 5388, 5283, 204, 2108, 258, 21820, 465...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[285, 140, 1528, 34777, 4205, 131, 116, 439, 1..."
4,4,Oscar host Rock to keep it clean\n\nOscar host...,The 40-year-old comedian caused a furore when ...,"[10109, 1713, 3140, 112, 376, 126, 1003, 10109...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[139, 15965, 1019, 121, 1623, 19306, 2145, 114..."
...,...,...,...,...,...,...
2303,2303,South African car demand surges\n\nCar manufac...,"New vehicle sales jumped 22% to 449,603 from a...","[793, 2636, 439, 1806, 52936, 2624, 2986, 122,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[351, 1143, 835, 8325, 35687, 112, 110, 40964,..."
2304,2304,Dollar hits new low versus euro\n\nThe US doll...,The US dollar has continued its record-breakin...,"[11566, 4341, 177, 580, 6075, 12333, 139, 787,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[139, 787, 4322, 148, 2059, 203, 1093, 121, 13..."
2305,2305,Bank holds interest rate at 4.75%\n\nThe Bank ...,CBI chief economist Ian McCafferty said the ec...,"[2039, 2758, 820, 872, 134, 384, 59516, 139, 2...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[49450, 3522, 21356, 9369, 39133, 26026, 4306,..."
2306,2306,BBC 'should allow more scrutiny'\n\nMPs have u...,The report said the Freeview digital service h...,"[6442, 1034, 19103, 763, 154, 16222, 131, 1981...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[139, 731, 243, 109, 67979, 1016, 292, 148, 19..."
2307,2307,Wal-Mart fights back at accusers\n\nTwo big US...,"Meanwhile, drugs group Eli Lilly is planning a...","[12282, 121, 18317, 12768, 247, 134, 77993, 11...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[8199, 108, 3239, 456, 15527, 27547, 117, 1062..."

In [22]:
for i in range(len(test.index)):

  final_test.loc[i] = [i,test.News.iloc[i],test.Summary.iloc[i], test_lis[i]['input_ids'],test_lis[i]['attention_mask'],test_sum[i]['input_ids']]

In [23]:
final_test

,id,dialogue,summary,input_ids,attention_mask,labels
0,0,Hi-tech posters guide commuters\n\nInteractive...,She said that there are no figures for how man...,"[4451, 121, 4665, 9106, 1245, 26627, 14656, 91...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[452, 243, 120, 186, 127, 220, 3432, 118, 199,..."
1,1,Gadgets galore on show at fair\n\nThe 2005 Con...,One of the key issues for keen gadget users is...,"[71693, 31177, 124, 403, 134, 2335, 139, 5109,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[614, 113, 109, 662, 618, 118, 5462, 14556, 78..."
2,2,"Lifestyle 'governs mobile choice'\n\nFaster, b...",Dr Bjorn said that people also used their came...,"[18558, 1034, 6897, 19048, 116, 944, 814, 131,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[982, 70097, 243, 120, 200, 163, 263, 153, 152..."
3,3,MP attacked by muggers in Kenya\n\nAn MP has h...,"He said in a statement: ""It was a frightening ...","[4145, 9656, 141, 11462, 23613, 115, 8607, 983...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[285, 243, 115, 114, 1736, 151, 198, 362, 140,..."
4,4,Brown names 16 March for Budget\n\nChancellor ...,"The full Finance Bill, with the Budget measure...","[3065, 1964, 1195, 1051, 118, 9346, 18858, 865...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[139, 357, 5227, 3014, 108, 122, 109, 9346, 25..."
...,...,...,...,...,...,...
766,766,British stars denied major Oscars\n\nBritish h...,"Cinematographer John Mathieson, who was nomina...","[1816, 3061, 6837, 698, 33925, 1816, 3840, 113...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[94842, 1084, 9875, 3317, 661, 108, 170, 140, ..."
767,767,Security warning over 'FBI virus'\n\nThe US Fe...,An attachment in the e-mail contains the virus...,"[2550, 4752, 204, 1034, 79598, 5807, 131, 139,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[983, 8992, 115, 109, 860, 121, 2873, 1733, 10..."
768,768,Digital guru floats sub-$100 PC\n\nNicholas Ne...,"He said one laptop per child could be "" very i...","[3322, 21459, 24251, 2672, 121, 46343, 2208, 1...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[285, 243, 156, 3813, 446, 667, 256, 129, 198,..."
769,769,UK rebate 'unjustified' - Chirac\n\nFrench pre...,The Tories said they would not cut spending bu...,"[926, 21876, 1034, 3036, 5904, 11427, 131, 233...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[139, 45379, 243, 157, 192, 146, 999, 2027, 15..."
770,770,Clyde 0-5 Celtic\n\nCeltic brushed aside Clyde...,": Varga 40, Thompson 48 pen, Petrov 60, Varga ...","[27762, 110, 31263, 15239, 15239, 14890, 3631,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[110, 151, 1328, 40633, 1466, 108, 8533, 3925,..."

In [24]:
for i in range(len(validate.index)):

  final_validate.loc[i] = [i,validate.News.iloc[i],validate.Summary.iloc[i], val_lis[i]['input_ids'], val_lis[i]['attention_mask'], val_sum[i]['input_ids']]

In [25]:
final_validate

,id,dialogue,summary,input_ids,attention_mask,labels
0,0,Brown calls for £5.5bn Aids fund\n\nGordon Bro...,But Aid charity Actionaid criticised Mr Brown'...,"[3065, 2101, 118, 14295, 107, 1343, 10970, 564...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[343, 9335, 4402, 5208, 17889, 29263, 1263, 30..."
1,1,Smith keen on Home series return\n\nScotland m...,Scotland manager Walter Smith has given his ba...,"[2862, 5462, 124, 1043, 679, 935, 4631, 2031, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[4631, 2031, 10704, 2862, 148, 634, 169, 7754,..."
2,2,Halo 2 heralds traffic explosion\n\nThe growin...,Service providers now need to make sure that t...,"[20952, 280, 36014, 116, 1619, 11335, 139, 122...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1255, 2350, 239, 217, 112, 193, 334, 120, 153..."
3,3,Iraq to invite phone licence bids\n\nIraq is t...,The ministry said that it wanted to increase I...,"[6052, 112, 4113, 685, 9853, 16154, 6052, 117,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[139, 4774, 243, 120, 126, 869, 112, 815, 6052..."
4,4,Sony PSP tipped as a 'must-have'\n\nSony's Pla...,Owning all 10 gadgets will set the gadget love...,"[6320, 28420, 23354, 130, 114, 1034, 18847, 12...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[63599, 149, 377, 11203, 138, 323, 109, 14556,..."
...,...,...,...,...,...,...
764,764,Virus poses as Christmas e-mail\n\nSecurity fi...,Anti-virus firm Sophos said that 10% of the e-...,"[29045, 10990, 130, 1174, 860, 121, 2873, 2550...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[6273, 121, 18089, 1419, 75741, 243, 120, 5029..."
765,765,Burglar defence guidelines issued\n\nHousehold...,British voters would reject the European const...,"[72631, 7909, 3625, 3020, 1087, 20504, 170, 33...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1816, 5567, 192, 12139, 109, 1489, 12929, 141..."
766,766,Chancellor rallies Labour voters\n\nGordon Bro...,"Responding to the speech, shadow chief secreta...","[18858, 28152, 9083, 5567, 8659, 3065, 148, 30...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[110, 42735, 112, 109, 3442, 108, 7572, 3522, ..."
767,767,Muslims discuss election concerns\n\nIssues th...,"""This meeting is not anti-party in particular,...","[10505, 1693, 2974, 2084, 16354, 120, 10505, 2...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[198, 287, 988, 117, 146, 1857, 121, 5834, 115..."
768,768,Parliament's record of scandal\n\nIn a locked ...,Labour has always maintained Mr Brown would ha...,"[7533, 131, 116, 1093, 113, 14570, 222, 114, 6...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[9083, 148, 329, 4099, 1263, 3065, 192, 133, 1..."

### These Dataframes are being saved as CSV files for reusability in different models

In [26]:
!mkdir -p "/content/drive/MyDrive/BBC_News_Tokenized"

In [28]:
final_train.to_csv("/content/drive/MyDrive/BBC_News_Tokenized/training_tokenized.csv")
final_test.to_csv("/content/drive/MyDrive/BBC_News_Tokenized/testing_tokenized.csv")
final_validate.to_csv("/content/drive/MyDrive/BBC_News_Tokenized/validation_tokenized.csv")

### Conversion to Dictionaries and finally Datasets for passing into LLM Trainer

In [29]:
traind = {'id': final_train['id'].to_list(),
          'dialogue': final_train['dialogue'].to_list(),
          'summary': final_train['summary'].to_list(),
          'input_ids': final_train['input_ids'].to_list(),
          'attention_mask' : final_train['attention_mask'].to_list(),
          'labels': final_train['labels'].to_list()}

In [30]:
testd = {'id': final_test['id'].to_list(),
          'dialogue': final_test['dialogue'].to_list(),
          'summary': final_test['summary'].to_list(),
          'input_ids': final_test['input_ids'].to_list(),
          'attention_mask' : final_test['attention_mask'].to_list(),
          'labels': final_test['labels'].to_list()}

In [31]:
vald = {'id': final_validate['id'].to_list(),
          'dialogue': final_validate['dialogue'].to_list(),
          'summary': final_validate['summary'].to_list(),
          'input_ids': final_validate['input_ids'].to_list(),
          'attention_mask' : final_validate['attention_mask'].to_list(),
          'labels': final_validate['labels'].to_list()}

In [32]:
from datasets import Dataset

traindj = Dataset.from_dict(traind)
testj = Dataset.from_dict(testd)
valdj = Dataset.from_dict(vald)

In [33]:
traindj

Dataset({
    features: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 2308
})

In [34]:
testj

Dataset({
    features: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 771
})

In [35]:
valdj

Dataset({
    features: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 769
})